name: Deploy to Render

on:
  push:
    branches:
      - main  # Apni branch yahan daalo agar 'main' nahi hai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d2hn6tbe5dus73eqdb0g?key=MpUBmzyLWrE"
