name: Deploy to Render

on:
  push:
    branches:
      - main  # apni branch name yahan daalo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
